editor:
  decorate_1: STAINED_GLASS_PANE
  decorate_2: STAINED_GLASS_PANE
  decorate_3: STAINED_GLASS_PANE
  decorate_4: STAINED_GLASS_PANE
  decorate_5: STAINED_GLASS_PANE
  name: SIGN
  lore: PAINTING
  chance: STRING
  mode: REDSTONE
  mode_attribute: HOPPER
  recipes: TORCH
  recipes_experience: ENDER_PEARL
  hot: TORCH
  time: COMPASS
  level: NETHER_STAR
  result_add_experience: POTION
  result_recipes_experience: POTION
  result_item: BREAD
  result_run: REDSTONE_BLOCK
  fail_add_experience: POTION
  fail_recipes_experience: POTION
  fail_item: BREAD
  fail_run: REDSTONE_BLOCK
  save: WOOL
  back: BARRIER
  empty: GHAST_TEAR
  fail_remove: BARRIER